### ISSUE TITLE
How can I call the trained model from Java?

### ISSUE THREAD

**Issue by devgz** [TinusGreen/captcha_cracking#1]
I see the curl request, but can you give us some example on how to send the request with java?

What parameters to send along to the API.

**Comment by TinusGreen** [comment]
The curl request should be used as baseline to create the request in whatever language you prefer. The curl request shows that you send two headers and two POST data objects.

From the following:
```
curl -X POST \
  http://localhost:9001/v1/models/yourmodelname:predict \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
  "signature_name": "serving_default",
  "inputs": {
     	"input": { "b64": "/9j/4AAQ==" }
  }
}'
```

You should see that you need to set the headers: `cache-control` and `content-type`. You should then send the data as a JSON object containing the `signature_name` and `inputs` where each `input` is a base64 encoded CAPTCHA.

I don't really use Java but I'd start looking at something like this: http://hc.apache.org/httpcomponents-client-ga/tutorial/html/fundamentals.html

In Python, using the requests library, it would look something like:

```
import requests
headers = {"cache-control" : "no-cache", "content-type" : "application/json"}
captcha = <base64 Encoded CAPTCHA>
r = requests.post("http://localhost:9001/v1/models/<model name>:predict", json={"signature_name": "serving_default", "inputs" : {"input" : {"b64" : captcha}}})
```

You can also use online converters to convert the curl request to the language of you choice.
