### ISSUE TITLE
No versions of servable saved_model

### ISSUE THREAD

**Issue by devgz** [TinusGreen/captcha_cracking#3]
> No versions of servable saved_model found under base path /home/captcha/Desktop/A-OCR-AmazonModel/exported-model/1

After inserting:

> tensorflow_model_server --port=9000 --rest_api_port=9001 --model_name=saved_model --model_base_path=/home/captcha/Desktop/A-OCR-AmazonModel/exported-model/1

VirtualBox: 
Ubunto 18.04

![virtualbox1](https://user-images.githubusercontent.com/39295947/51502460-3c003780-1da4-11e9-937b-0a27e7a98cf8.PNG)
![virtualbox2](https://user-images.githubusercontent.com/39295947/51502461-3c003780-1da4-11e9-88eb-5b8c5f869137.PNG)

Thanks again, Im not sure why I cant run it

**Comment by TinusGreen** [comment]
`tensorflow_model_server --port=9000 --rest_api_port=9001 --model_name=saved_model --model_base_path="/home/captcha/Desktop/A-OCR-AmazonModel/exported-model"`

This is a tutorial on training CAPTCHA models for research purposes. If you require more information on tensorflow models or servers please go visit their site, forums, and Github pages.
